// <auto-generated />
namespace NZNA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201809282139432_newdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
